name: 🔂 CloudFlare Pages Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  preview:
    uses: ./.github/workflows/service_build-static-site.yml
    secrets: inherit